server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jn_blog?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: Andy
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    # 文件上传
    multipart:
      # 单个上传文件的最大允许大小
      max-file-size: 20MB
      # HTTP请求中包含的所有文件的总大小的最大允许值
      max-request-size: 20MB

  # redis
  redis:
#    host: 120.46.48.88  # 虚拟机
    host: localhost  # 虚拟机
    port: 6379
#    port: 6333


mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto


# 打开七牛云，找到密钥管理，把相关信息填写到下面3行，会被jn-blog-web工程的OOSTest类获取
myoss:
  xxaccessKey: Mwk7aurh7shvgAcJpiXnVe3sCzEtMMZF5CTXuhlv
  xxsecretKey: Tl5KufdrduO6ewMQ253lnR9tytt4TKk-PoMiLFLg
  xxbucket: jn-blog-web
